server:
  port: 8085

downloading-listener:
  stream: download:stream
  consumer: ${HOSTNAME:local}

formatting-listener:
  stream: formatting:stream
  consumer: ${HOSTNAME:local}
  group: main-formatter-group

save-s3-listener:
  stream: save:s3:stream
  consumer: ${HOSTNAME:local}
  group: main-saver-group


storage:
  s3:
    top-prefix: content
    hls-playlist-content-type: "application/vnd.apple.mpegurl"
  minio:
    credentials:
      endpoint: http://127.0.0.1:9000/
      name: "minioadmin"
      password: "minioadmin123"


spring:
  config:
    import: classpath:config/video-presets.yaml
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: film_download
    default-schema: film_download
  datasource:
    url: jdbc:postgresql://localhost:5432/movie?currentSchema=film_download
    username: movie_user
    password: movie
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379




logging:
  level:
    org.apache.ibatis: DEBUG
    org.film.parser.feature.movie.detail.repository: TRACE
    org.film.parser.feature.playlist.repository: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    org.springframework.web.client.RestTemplate: DEBUG
    org.apache.http: DEBUG
    httpclient.wire: DEBUG
    org.film.parser: DEBUG
